### PR TITLE
Make blockvaluesgui pageable+slotable

### LINKED ISSUE #287: ArrayIndexOutOfBounds exception
> [19:28:54] [Craft Scheduler Thread - 104/WARN]: [IridiumSkyblock] Plugin IridiumSkyblock v3.0.6 generated an exception while executing task 153120
> java.lang.ArrayIndexOutOfBoundsException: 27
> 	at java.util.Arrays$ArrayList.set(Arrays.java:3846) ~[?:1.8.0_282]
> 	at net.minecraft.server.v1_16_R3.NonNullList.set(SourceFile:53) ~[patched_1.16.5.jar:git-Paper-715]
> 	at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftInventoryCustom$MinecraftInventory.setItem(CraftInventoryCustom.java:141) ~[patched_1.16.5.jar:git-Paper-715]
> 	at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftInventory.setItem(CraftInventory.java:100) ~[patched_1.16.5.jar:git-Paper-715]
> 	at com.iridium.iridiumskyblock.gui.BlockValueGUI.addContent(BlockValueGUI.java:49) ~[?:?]
> 	at com.iridium.iridiumskyblock.gui.GUI.lambda$getInventory$0(GUI.java:43) ~[?:?]
> 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-715]
> 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-715]
> 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-715]
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_282]
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_282]
> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]

### PR DESCRIPTION
**Pull request by MertUnverdi**
fixes #287

### CODE REVIEW

**Comment by dlsf** [comment]
You should test how well this change works with a pre-existing config, I could imagine that it won't show items at all because it's page 0 by default

**Comment by MertUnverdi** [comment]
@dlsf i'll add null or page items to page 1, ik it weird a bit but i should :(

File: src/main/java/com/iridium/iridiumskyblock/configs/BlockValues.java [hunk 1]
```diff
@@ -17,25 +17,24 @@
 public class BlockValues {
 
     public Map<XMaterial, ValuableBlock> blockValues = ImmutableMap.<XMaterial, ValuableBlock>builder()
-            .put(XMaterial.IRON_BLOCK, new ValuableBlock(3.0, "&b&lIron Block", 10))
```
[the remark this answers is not in the document]
Comment (MertUnverdi) [reply src/main/java/com/iridium/iridiumskyblock/configs/BlockValues.java:20]: ooof peaches u're tooo old check the commits -,-

File: src/main/java/com/iridium/iridiumskyblock/gui/BlockValueGUI.java [hunk 2]
```diff
@@ -48,7 +48,13 @@ public void addContent(Inventory inventory) {
...
         if (guiType == BlockValueType.BLOCK) {
             IridiumSkyblock.getInstance().getBlockValues().blockValues.entrySet().stream()
-                    .filter(valuableBlockEntry -> valuableBlockEntry.getValue().page == page)
+                    .filter(valuableBlockEntry -> {
+                        if (this.page == 1) {
+                            return valuableBlockEntry.getValue().page <= 1;
+                        } else {
+                            return valuableBlockEntry.getValue().page == page;
+                        }
+                    })
```
Comment (dlsf) [inline src/main/java/com/iridium/iridiumskyblock/gui/BlockValueGUI.java:57]: Looks cleaner in my opinion but it's up to you
```suggestion
                    .filter(valuableBlockEntry -> (valuableBlockEntry.getValue().page < 1 ? 1 :  valuableBlockEntry.getValue().page) == page)
```

File: src/main/java/com/iridium/iridiumskyblock/gui/BlockValueGUI.java [hunk 3]
```diff
@@ -58,7 +64,13 @@ public void addContent(Inventory inventory) {
...
         } else if (guiType == BlockValueType.SPAWNER) {
             IridiumSkyblock.getInstance().getBlockValues().spawnerValues.entrySet().stream()
-                    .filter(valuableSpawnerEntry -> valuableSpawnerEntry.getValue().page == page)
+                    .filter(valuableSpawnerEntry -> {
+                        if (this.page == 1) {
+                            return valuableSpawnerEntry.getValue().page <= 1;
+                        } else {
+                            return valuableSpawnerEntry.getValue().page == page;
+                        }
+                    })
```
Comment (dlsf) [inline src/main/java/com/iridium/iridiumskyblock/gui/BlockValueGUI.java:73]: Same here
```suggestion
                    .filter(valuableSpawnerEntry -> (valuableSpawnerEntry.getValue().page < 1 ? 1 :  valuableSpawnerEntry.getValue().page) == page)
```

**Review by dlsf — CHANGES_REQUESTED** [review]

File: src/main/java/com/iridium/iridiumskyblock/gui/BlockValueGUI.java (hunk 2 above)
Comment (MertUnverdi) [reply src/main/java/com/iridium/iridiumskyblock/gui/BlockValueGUI.java:57]: we must check the page is 1

File: src/main/java/com/iridium/iridiumskyblock/gui/BlockValueGUI.java [hunk 4]
```diff
@@ -73,7 +82,15 @@ public void addContent(Inventory inventory) {
      */
     @Override
     public void onInventoryClick(InventoryClickEvent event) {
-        // Don't do anything here, it gets cancelled automatically
+        Player player = (Player) event.getWhoClicked();
+        if (event.getSlot() == getNoItemGUI().size - 7 && page > 1) {
+            player.openInventory(new BlockValueGUI(page - 1, guiType).getInventory());
```
Comment (dlsf) [inline src/main/java/com/iridium/iridiumskyblock/gui/BlockValueGUI.java:87]: In other GUIs we just changed the value of the page variable and called `player.openInventory(getInventory())`

File: src/main/java/com/iridium/iridiumskyblock/gui/BlockValueGUI.java [hunk 5]
```diff
@@ -41,20 +43,27 @@ public void addContent(Inventory inventory) {
...
         } else if (guiType == BlockValueType.SPAWNER) {
-            for (Map.Entry<EntityType, ValuableBlock> valuableSpawner : IridiumSkyblock.getInstance().getBlockValues().spawnerValues.entrySet()) {
-                EntityType spawnerType = valuableSpawner.getKey();
-                ValuableBlock spawnerInfo = valuableSpawner.getValue();
-                ItemStack spawnerItem = ItemStackUtils.makeItem(XMaterial.SPAWNER, 1, StringUtils.color(spawnerInfo.name), getColoredValueLore(spawnerInfo.value));
-                inventory.setItem(spawnerInfo.slot, spawnerItem);
-            }
+            IridiumSkyblock.getInstance().getBlockValues().spawnerValues.entrySet().stream()
+                    .filter(valuableSpawnerEntry -> (page == 1 ? valuableSpawnerEntry.getValue().page <= 1 : valuableSpawnerEntry.getValue().page == page))
+                    .forEachOrdered(valuableSpawner -> {
```
Comment (dlsf) [inline src/main/java/com/iridium/iridiumskyblock/gui/BlockValueGUI.java:62]: You should probably use the map method here. It's up to you but I can help you with it if you want

**Review by dlsf — CHANGES_REQUESTED** [review]

File: src/main/java/com/iridium/iridiumskyblock/gui/BlockValueGUI.java (hunk 5 above)
Comment (MertUnverdi) [reply src/main/java/com/iridium/iridiumskyblock/gui/BlockValueGUI.java:62]: how :/

File: src/main/java/com/iridium/iridiumskyblock/gui/BlockValueGUI.java (hunk 4 above)
Comment (MertUnverdi) [reply src/main/java/com/iridium/iridiumskyblock/gui/BlockValueGUI.java:87]: i did 👍🏻

File: src/main/java/com/iridium/iridiumskyblock/gui/BlockValueGUI.java (hunk 5 above)
Comment (MertUnverdi) [reply src/main/java/com/iridium/iridiumskyblock/gui/BlockValueGUI.java:62]: we must have entryset and map method will get only the value without key

File: src/main/java/com/iridium/iridiumskyblock/gui/BlockValueGUI.java (hunk 4 above)
Comment (dlsf) [reply src/main/java/com/iridium/iridiumskyblock/gui/BlockValueGUI.java]: 1) Do `page++` instead of `page+=1` (the indentation is bad too)
2) Remove the page argument from the constructor

File: src/main/java/com/iridium/iridiumskyblock/gui/BlockValueGUI.java (hunk 5 above)
Comment (dlsf) [reply src/main/java/com/iridium/iridiumskyblock/gui/BlockValueGUI.java:62]: Can I do it for you?

Comment (MertUnverdi) [reply src/main/java/com/iridium/iridiumskyblock/gui/BlockValueGUI.java:62]: ofc pls <3

File: src/main/java/com/iridium/iridiumskyblock/gui/BlockValueGUI.java (hunk 4 above)
Comment (MertUnverdi) [reply src/main/java/com/iridium/iridiumskyblock/gui/BlockValueGUI.java]: off why i did like this idk lol

File: src/main/java/com/iridium/iridiumskyblock/gui/BlockValueGUI.java (hunk 5 above)
Comment (dlsf) [reply src/main/java/com/iridium/iridiumskyblock/gui/BlockValueGUI.java:61]: Nvm

**Review by dlsf — APPROVED** [review]
